name: Performance Execution

on:
  workflow_dispatch:
    inputs:
      testSuite:
        type: string
        description: 'testSuite'
        required: true
        default: 'restfulapi.RestfulApiTest'
      concurrent:
        type: string
        description: 'Quantity of users'
        required: true
        default: '10'

jobs:
  execrestfulapi:
    runs-on: ubuntu-latest
    name: Executing Restful API
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute test
        run: gradle gatlingRun --simulation=${{ inputs.testSuite }} -DconcurrentUsers=${{ inputs.concurrent }}

      - name: Save report
        if: ${{always()}}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: gatling report
          path: ./build/reports/gatling