name: Performance Execution

on:
  workflow_dispatch:
    inputs:
      testSuite:
        default: 'restfulapi.RestfulApiTest'
jobs:
  execRestfulApi:
    runs-on: ubuntu-latest
    name: Executing Restful API Test
    steps:
      - name: Checkout code
        uses: action/checkout@v2
