name: Performance Execution

on:
  workflow_dispatch:
    inputs:
      testSuite:
        type: string
        description: 'testSuite'
        required: true
        default: 'restfulapi.RestfulApiTest'

jobs:
  execrestfulapi:
    runs-on: ubuntu-latest
    name: Executing Restful API
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
